Authentication
mrjvs/42-webserv pull request #52
Opened 2021-04-04 08:50 UTC by piramidebouwer

#46

2021-04-05 08:50 UTC, mrjvs requested changes
just a few :)

2021-04-05 08:50 UTC, mrjvs commented on src/server/http/HTTPResponder.cpp
> +	}
check route block along with 401 error code if the header has to be set.

also dont set an entire response, only set the header

2021-04-05 08:50 UTC, mrjvs commented on src/server/http/HTTPResponder.cpp
> +	buf[ret] = '\0';
read in a while loop to get everything, if it passes the max size (like 10kb) then return error + log

2021-04-05 08:50 UTC, mrjvs commented on src/server/http/HTTPResponder.cpp
> +	std::string file(buf); // TODO parse file?
file += buf; (for the loop)

2021-04-05 08:50 UTC, mrjvs commented on src/server/http/HTTPResponder.cpp
> +		return false;
check != 0 instead of == npos

otherwise header `HelloworldBasic asdfasdf` would be valid

2021-04-05 08:50 UTC, mrjvs commented on src/server/http/HTTPResponder.cpp
> +	std::vector<std::string> users = utils::split(file, "\n");
rename, example: userPasswordPairs

2021-04-05 08:50 UTC, mrjvs commented on src/server/http/HTTPResponder.cpp
> +	if (route->getAuthBasic().size()) {
check with .empty()

2021-04-05 08:50 UTC, mrjvs commented on src/server/http/HTTPResponder.cpp
> +	if (route->getAuthBasic().size()) {
and move entire check into file serving block

2021-04-05 08:50 UTC, mrjvs commented on src/server/http/HTTPResponder.cpp
> +			handleError(client, server, route, 400); // TODO 403 forbidden? is this right in all cases
yes use 403

2021-04-05 08:50 UTC, mrjvs commented on src/server/http/HTTPResponder.cpp
> +		return false;
throw here

2021-04-05 08:50 UTC, mrjvs commented on src/server/http/HTTPResponder.cpp
> +		else if (!checkCredentials(route->getAuthBasicUserFile(), it->second)) {
try catch this. depending on the error, throw 500 (syscalls break) or 400 (request invalid)

2021-04-05 08:50 UTC, mrjvs commented on src/utils/base64.cpp
> +	}
try making this more readable (at least bit shifting as possible)
where possible, explain with comments whats going on (especially where you shift with bits)

2021-04-07 14:22 UTC, pmerku requested changes

2021-04-07 14:22 UTC, pmerku commented on makefile
> +	valgrind --undef-value-errors=no --leak-check=full ./$(NAME)
Change back, probably got changed in merging

2021-04-07 14:22 UTC, pmerku commented on src/server/http/HTTPClient.cpp
> +HTTPClient::HTTPClient(FD clientFd, int port, long host, sockaddr_in cli_addr): _fd(clientFd), _port(port), _host(host), _associatedFds(), _cli_addr(cli_addr), writeState(NO_RESPONSE), connectionStat
Indent so it's not too long

2021-04-08 14:15 UTC, merged