Proper handling of HTTP methods
mrjvs/42-webserv pull request #58
Opened 2021-04-06 19:38 UTC by mrjvs

resolves #56 and resolves #45

2021-04-07 14:15 UTC, pmerku requested changes

2021-04-07 14:15 UTC, pmerku commented on src/server/handlers/StandardHandler.cpp
> +}
This seems a bit unnecessary?

2021-04-07 14:20 UTC, piramidebouwer approved these changes

2021-04-08 14:07 UTC, pmerku approved these changes

2021-04-08 14:08 UTC, merged