Cleaning todos
mrjvs/42-webserv pull request #59
Opened 2021-04-08 16:57 UTC by pmerku

- [ ] parser
- [ ] directory traversal detection

2021-04-09 10:53 UTC, mrjvs requested changes
also try doRead again with CGI

2021-04-09 10:53 UTC, mrjvs commented on src/server/http/HTTPParser.cpp
> +				}
```
if (*valueIt == "chunked")
  _isChunked = true;
else {
  globalLogger.logItem(logger::ERROR, "Not supported transfer encoding");
					data.parseStatusCode = 400;
					return ERROR;
}
```

2021-04-09 10:53 UTC, mrjvs commented on src/utils/Uri.cpp
> +
make seperate (static function or bool in parameter) check that only applies in the parser. directory traversal is used in config options.

2021-04-09 10:53 UTC, mrjvs commented on src/utils/Uri.cpp
> +
(also check with telnet and nginx if it should be 400'ed or erased)

2021-04-12 09:52 UTC, mrjvs approved these changes

2021-04-12 09:54 UTC, piramidebouwer approved these changes

2021-04-12 10:04 UTC, merged