Docker
mrjvs/42-webserv pull request #60
Opened 2021-04-09 09:20 UTC by pmerku

added docker to the project

2021-04-09 09:23 UTC, pmerku commented
Unfortunately it has the commits from the draft pr

2021-04-09 11:00 UTC, mrjvs requested changes
also remove HTTPParser.cpp from here

2021-04-09 11:00 UTC, mrjvs commented on dockerfile
> +CMD ["/bin/sh", "run.sh"]
dont use run.sh
instead use:

```
ENTRYPOINT ./not-apache # executable
CMD -c -v -f "../resources/example-configs/basic.conf" # default arguments. can easily be changed with docker run or another docker file
```

2021-04-09 12:05 UTC, mrjvs approved these changes

2021-04-12 09:01 UTC, piramidebouwer approved these changes

2021-04-12 09:49 UTC, merged