page 404 generator plugin
mrjvs/42-webserv pull request #70
Opened 2021-04-14 14:16 UTC by pmerku

2021-04-14 18:54 UTC, mrjvs requested changes

2021-04-14 18:54 UTC, mrjvs commented on src/plugins/PageGenerator.cpp
> +				+ std::string("</div></div></div></body></html>")
Use a `static const std::string` for the template and when you need to generate, just copy if, find something like `{{FACT}}` and replace it with your fact. (I did something similar in `ConfigException::PrettyPrint()`, you can look at that as example)

2021-04-14 18:54 UTC, mrjvs commented on src/plugins/PageGenerator.cpp
> +		}
maybe do it on the constructor?

2021-04-15 11:18 UTC, mrjvs approved these changes

2021-04-15 15:50 UTC, piramidebouwer approved these changes

2021-04-15 15:54 UTC, merged