jsonStatAPI + terminal commands
mrjvs/42-webserv pull request #73
Opened 2021-04-15 11:58 UTC by piramidebouwer

TODO terminal command shutdown

2021-04-15 12:30 UTC, mrjvs requested changes

2021-04-15 12:30 UTC, mrjvs commented on src/_includes/server/http/BodyBuilder.hpp
> +	private:
Rename to JsonBodyBuilder

2021-04-15 12:30 UTC, mrjvs commented on src/plugins/JsonStatAPI.cpp
> +	std::string fileType = client.file.path.substr(client.file.path.rfind(".")+1);
use `client.file.getExt()`

2021-04-15 12:30 UTC, mrjvs commented on src/plugins/JsonStatAPI.cpp
> +		.mode("mode", buf.st_mode)
Use camelCase for naming

2021-04-15 12:30 UTC, mrjvs commented on src/server/responder/serving.cpp
> +	}
Move the hook to line 35 of this file. that will also include serving of index files

2021-04-15 12:30 UTC, mrjvs commented on src/server/terminal/TerminalResponder.cpp
>  }
Handle commands differently:
1. split on whitespace (args[])
2. compare args[0] with list of available commands. if not found send usage
3. for load/unload, find args[1] (the plugin), display error if not found and if already loaded/unloaded
4. make sure to send success

2021-04-15 12:30 UTC, mrjvs commented on src/server/terminal/TerminalResponder.cpp
>  }
And for exit, pass a Server class pointer to the arguments of respond(); (which is `this` when you call it)
then just call `server->shutdown();` to exit

2021-04-15 12:30 UTC, mrjvs commented on src/server/responder/serving.cpp
> +				client.data.response.setResponse(client.data.response.builder.build());
move to hook code

2021-04-15 12:30 UTC, mrjvs commented on src/plugins/JsonStatAPI.cpp
> +
Set mimeType of `client.data.response.builder` to `application/json`

2021-04-15 12:30 UTC, mrjvs commented on src/server/http/BodyBuilder.cpp
> +	return _body;
Store a std::map<std::string,std::string> and build at the end

2021-04-15 12:30 UTC, mrjvs commented on resources/example-configs/cgi.conf
> +
remove this file

2021-04-15 12:33 UTC, mrjvs commented
also strmode doesnt exist on linux. make your own implementation using [S_IS* macros](https://www.gnu.org/software/libc/manual/html_node/Testing-File-Type.html)

2021-04-15 15:52 UTC, mrjvs requested changes

2021-04-15 15:52 UTC, mrjvs commented on src/server/responder/serving.cpp
> +
```suggestion
	for (plugin::PluginContainer::pluginIterator it = globalPlugins.begin(); it != globalPlugins.end(); ++it) {
		if (it->second && it->first->onFileServing(client)) {
			return;
		}
	}
```

2021-04-15 15:52 UTC, mrjvs commented on src/server/terminal/TerminalResponder.cpp
> +		}
add plugin not found for this if branch

2021-04-15 15:52 UTC, mrjvs commented on src/server/terminal/TerminalResponder.cpp
>  	globalLogger.logItem(logger::INFO, "Handled terminal command :)");
you can remove this line now

2021-04-15 15:52 UTC, mrjvs commented on src/_includes/plugins/JsonStatAPI.hpp
> +	//TODO MAP VOOR KEYS om dubbele te voorkomen
remove todo, already done

2021-04-15 15:59 UTC, mrjvs commented
also do all todos in code

2021-04-16 13:29 UTC, mrjvs requested changes
make it compile then all is good (you can check the compilation logs at the bottom of the pr)

2021-04-16 14:22 UTC, mrjvs approved these changes

2021-04-16 14:23 UTC, pmerku approved these changes

2021-04-16 14:23 UTC, merged